---
name: Tag Docker
on:
  push:
    tags:
    - v[0-9]*.[0-9]*.[0-9]*+ffreville.[0-9]*
jobs:

  # -- docker ------------------------------------------------------------------

  docker-push:
    name: Docker Push
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      timeout-minutes: 2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      timeout-minutes: 2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      timeout-minutes: 2

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
        driver-opts: |
          image=moby/buildkit:master
          network=host
      timeout-minutes: 2

    # This step is needed to expose ACTIONS_CACHE_URL & ACTIONS_RUNTIME_TOKEN to
    # docker buildx so that it can cache build steps. 
    - name: Expose GitHub Runtime env vars
      uses: crazy-max/ghaction-github-runtime@v2
      timeout-minutes: 2

    - name: Build & Push docker image
      env:
        GOPRIVATE_GITHUB_TOKEN: ${{ secrets.GOPRIVATE_GITHUB_TOKEN }}
      run: |
        make docker-push DOCKER_BUILDX_PLATFORMS=linux/amd64
